# Generated by Django 5.1.6 on 2025-03-20 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportaudit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='audit',
            name='yearEnd',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='audit',
            name='yearStart',
            field=models.IntegerField(default=0),
        ),
    ]
