# Generated by Django 5.1.6 on 2025-03-20 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportaudit', '0002_alter_audit_date_alter_audit_yearend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainreport',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportaudit.audit'),
        ),
    ]
