# Generated by Django 5.1.6 on 2025-03-20 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportaudit', '0003_alter_mainreport_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportaudit.customer'),
        ),
    ]
