# Generated by Django 5.1.6 on 2025-03-20 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportaudit', '0004_alter_audit_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reportaudit.customer'),
        ),
        migrations.AlterField(
            model_name='yearreportdata',
            name='yearReports',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportaudit.mainreport'),
        ),
    ]
