# Generated by Django 5.1.6 on 2025-03-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportaudit', '0005_alter_audit_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yearreportdata',
            old_name='ob',
            new_name='A0',
        ),
        migrations.RenameField(
            model_name='yearreportdata',
            old_name='oc',
            new_name='B0',
        ),
    ]
