# Generated by Django 5.1.6 on 2025-03-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportaudit', '0006_rename_ob_yearreportdata_a0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearreportdata',
            name='A57',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='A58',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='A59',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='A60',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='A61',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='A62',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='B57',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='B58',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='B59',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='B60',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='B61',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='B62',
            field=models.IntegerField(default=0),
        ),
    ]
