# Generated by Django 5.1.6 on 2025-03-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportaudit', '0007_yearreportdata_a57_yearreportdata_a58_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearreportdata',
            name='obeservations',
            field=models.TextField(default='default'),
        ),
    ]
