# Generated by Django 5.1.6 on 2025-03-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportaudit', '0008_yearreportdata_obeservations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearreportdata',
            name='obeservations',
        ),
        migrations.AddField(
            model_name='audit',
            name='obeservations',
            field=models.TextField(default='default'),
        ),
    ]
