# Generated by Django 5.1.6 on 2025-03-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportaudit', '0009_remove_yearreportdata_obeservations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='date',
            field=models.DateField(),
        ),
    ]
