# Generated by Django 5.1.6 on 2025-03-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportaudit', '0010_alter_audit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
