# Generated by Django 5.1.6 on 2025-03-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportaudit', '0011_alter_audit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='obeservations',
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='ae1',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='ae10',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='ae11',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='ae12',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='ae13',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='ae14',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='ae15',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='ae16',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='ae17',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='ae2',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='ae3',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='ae4',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='ae5',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='ae6',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='ae7',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='ae8',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='ae9',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='be1',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='be10',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='be11',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='be12',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='be13',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='be14',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='be15',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='be16',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='be17',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='be18',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='be19',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='be2',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='be20',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='be3',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='be4',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='be5',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='be6',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='be7',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='be8',
            field=models.TextField(default='Enter Field'),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='be9',
            field=models.TextField(default='Enter Field'),
        ),
    ]
