# Generated by Django 5.1.6 on 2025-03-23 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportaudit', '0013_rename_ae1_yearreportdata_ae1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yearreportdata',
            old_name='ae7',
            new_name='Ae7',
        ),
    ]
