# Generated by Django 5.1.6 on 2025-03-24 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportaudit', '0016_cluster_alter_customer_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cluster',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='reportaudit.cluster'),
        ),
    ]
