# Generated by Django 5.1.6 on 2025-03-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportaudit', '0017_alter_customer_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='observations',
            field=models.TextField(default=''),
        ),
    ]
