# Generated by Django 5.1.6 on 2025-03-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportaudit', '0018_audit_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='observations2',
            field=models.TextField(default=''),
        ),
    ]
