# Generated by Django 5.1.6 on 2026-05-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportaudit', '0020_alter_audit_observations2_alter_yearreportdata_ea1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearreportdata',
            name='A63',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='A64',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='A65',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='A66',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='A67',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='A68',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='A69',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='A70',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='B63',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='B64',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='B65',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='B66',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='B67',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='B68',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='B69',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yearreportdata',
            name='B70',
            field=models.IntegerField(default=0),
        ),
    ]
