# Generated by Django 5.1.6 on 2026-05-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportaudit', '0021_yearreportdata_a63_yearreportdata_a64_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='observationP1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audit',
            name='observationP2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audit',
            name='observationP3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audit',
            name='observationP4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audit',
            name='observationP5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audit',
            name='observationP6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audit',
            name='observationP7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audit',
            name='observationRequired',
            field=models.BooleanField(default=False),
        ),
    ]
