# Generated by Django 5.1.6 on 2026-05-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportaudit', '0022_audit_observationp1_audit_observationp2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='observationValue1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='audit',
            name='observationValue2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='audit',
            name='observationValue3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='audit',
            name='observationValue4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='audit',
            name='observationValue5',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='audit',
            name='observationValue6',
            field=models.TextField(default=''),
        ),
    ]
