# Generated by Django 5.1.6 on 2026-05-24 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportaudit', '0023_audit_observationvalue1_audit_observationvalue2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='table1Row1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audit',
            name='table1Row10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audit',
            name='table1Row2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audit',
            name='table1Row3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audit',
            name='table1Row4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audit',
            name='table1Row5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audit',
            name='table1Row6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audit',
            name='table1Row7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audit',
            name='table1Row8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audit',
            name='table1Row9',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audit',
            name='table2Row1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audit',
            name='table2Row10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audit',
            name='table2Row2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audit',
            name='table2Row3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audit',
            name='table2Row4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audit',
            name='table2Row5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audit',
            name='table2Row6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audit',
            name='table2Row7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audit',
            name='table2Row8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audit',
            name='table2Row9',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ObservationTablerows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observationTable', models.IntegerField(choices=[(1, 'Table1'), (2, 'Table2')])),
                ('col1', models.TextField(default='')),
                ('col2', models.TextField(default='')),
                ('col3', models.TextField(default='')),
                ('col4', models.TextField(default='')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportaudit.audit')),
            ],
        ),
    ]
