# Generated by Django 5.1.6 on 2026-05-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportaudit', '0024_audit_table1row1_audit_table1row10_audit_table1row2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationtablerows',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
