# Generated by Django 5.1.6 on 2026-05-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportaudit', '0025_observationtablerows_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationtablerows',
            name='col5',
            field=models.TextField(default=''),
        ),
    ]
