# Generated by Django 5.1.6 on 2026-05-24 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportaudit', '0026_observationtablerows_col5'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit',
            old_name='table1Row1',
            new_name='table1Row10B',
        ),
        migrations.RenameField(
            model_name='audit',
            old_name='table1Row10',
            new_name='table1Row1B',
        ),
        migrations.RenameField(
            model_name='audit',
            old_name='table1Row2',
            new_name='table1Row2B',
        ),
        migrations.RenameField(
            model_name='audit',
            old_name='table1Row3',
            new_name='table1Row3B',
        ),
        migrations.RenameField(
            model_name='audit',
            old_name='table1Row4',
            new_name='table1Row4B',
        ),
        migrations.RenameField(
            model_name='audit',
            old_name='table1Row5',
            new_name='table1Row5B',
        ),
        migrations.RenameField(
            model_name='audit',
            old_name='table1Row6',
            new_name='table1Row6B',
        ),
        migrations.RenameField(
            model_name='audit',
            old_name='table1Row7',
            new_name='table1Row7B',
        ),
        migrations.RenameField(
            model_name='audit',
            old_name='table1Row8',
            new_name='table1Row8B',
        ),
        migrations.RenameField(
            model_name='audit',
            old_name='table1Row9',
            new_name='table1Row9B',
        ),
        migrations.RenameField(
            model_name='audit',
            old_name='table2Row1',
            new_name='table2Row10B',
        ),
        migrations.RenameField(
            model_name='audit',
            old_name='table2Row10',
            new_name='table2Row1B',
        ),
        migrations.RenameField(
            model_name='audit',
            old_name='table2Row2',
            new_name='table2Row2B',
        ),
        migrations.RenameField(
            model_name='audit',
            old_name='table2Row3',
            new_name='table2Row3B',
        ),
        migrations.RenameField(
            model_name='audit',
            old_name='table2Row4',
            new_name='table2Row4B',
        ),
        migrations.RenameField(
            model_name='audit',
            old_name='table2Row5',
            new_name='table2Row5B',
        ),
        migrations.RenameField(
            model_name='audit',
            old_name='table2Row6',
            new_name='table2Row6B',
        ),
        migrations.RenameField(
            model_name='audit',
            old_name='table2Row7',
            new_name='table2Row7B',
        ),
        migrations.RenameField(
            model_name='audit',
            old_name='table2Row8',
            new_name='table2Row8B',
        ),
        migrations.RenameField(
            model_name='audit',
            old_name='table2Row9',
            new_name='table2Row9B',
        ),
    ]
